theme = "congo"

baseURL = "https://farhaduneci.github.io/"
defaultContentLanguage = "en"

enableRobotsTXT = true
enableGitInfo = true

paginate = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]
