theme = "congo"

baseURL = "https://farhaduneci.github.io/softwarexplore/"
defaultContentLanguage = "en"

enableRobotsTXT = true

paginate = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]
