languageCode = "en"
languageName = "English"
weight = 1

title = "SoftwareXplore"

[params]
isoCode = "en"
displayName = "EN"
rtl = false

dateFormat = "2 January 2006"

mainSections = ["section1", "section2"]
description = "Farhad Uneci's blog, Tales of a Software Adventurer."

[author]
name = "Farhad Uneci"
image = "images/farhad.jpg"
headline = "Software engineering athirst."
bio = "Hard-working, highly motivated individual with proficiency in Python and Django. A tech enthusiast, an open-source advocate, and a software adventurer."

links = [
  { email = "mailto:farhaduneci@gmail.com"},
  { github = "https://github.com/farhaduneci" },
  { linkedin = "https://linkedin.com/in/farhaduneci" },
  { telegram = "https://t.me/feriun" },
  { twitter = "https://twitter.com/feriunn" },
]
